---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: faas-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://openfaas.github.io/faas-netes/
  timeout: 3m
