---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./aqua-charts.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./crunchydata.yaml
  - ./deliveryhero-charts.yaml
  - ./descheduler-charts.yaml
  - ./emberstack-charts.yaml
  - ./emqx-charts.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./faas-netes-charts.yaml
  - ./fairwinds-charts.yaml
  - ./falco-security-charts.yaml
  - ./gitea-charts.yaml
  - ./grafana-charts.yaml
  - ./hajimari.yaml
  - ./ingress-nginx-charts.yaml
  - ./intel.yaml
  - ./itzg-minecraft-charts.yaml
  - ./jetstack.yaml
  - ./k8s-at-home-charts.yaml
  - ./kasten-charts.yaml
  - ./kubernetes-dashboard-charts.yaml
  - ./metallb-charts.yaml
  - ./metrics-server.yaml
  - ./nfs-subdir-external-provisioner-charts.yaml
  - ./node-feature-discovery-charts.yaml
  - ./oauth2-proxy-charts.yaml
  - ./obeone-charts.yaml
  - ./onechart.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph-charts.yaml
  - ./s3gw-charts.yaml
  - ./stakater-charts.yaml
  - ./stevehipwell.yaml
  - ./vector-charts.yaml
  - ./weave-gitops.yaml
  - ./weaveworks.yaml