---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.2.0.100-10.2.0.200
  SVC_HOME_ASSISTANT_ADDRESS: 10.2.0.101
  SVC_NGINX_ADDR: 10.2.0.100
  SVC_MOSQUITTO_ADDR: 10.2.0.103
  SVC_SYSLOG_ADDR: 10.2.0.111
  SVC_PLEX_ADDR: 10.2.0.105
  QB_PLEX_IP: 10.2.0.106
  LB_LOKI_IP: 10.2.0.110
  LB_HOMECRAFT: 10.2.0.120
  TIMEZONE: 'America/New_York'
